# Generated by tools/generate_mqtt_catalog.py; do not edit.
import json

CATALOG = json.loads("{\"brokers\": {\"emqx\": {\"host\": \"broker.emqx.io\", \"tls_port\": 8883}, \"hivemq\": {\"host\": \"broker.hivemq.com\", \"tls_port\": 8883}, \"mosquitto\": {\"host\": \"test.mosquitto.org\", \"tls_port\": 8886}}, \"limits\": {\"encoded_packet_bytes\": 1048576, \"global_inflight_bytes\": 8388608, \"global_inflight_packets\": 12, \"max_chunk_feedback\": 1024, \"max_peer_routes\": 10000, \"max_tracked_attempts\": 4096, \"per_peer_chunk_feedback\": 64, \"per_peer_inflight_bytes\": 2097152, \"reserved_control_packets\": 2, \"small_packet_bytes\": 65536, \"unmeasured_chunk_bytes_per_second\": 262144}, \"selection\": \"automatic\", \"timing\": {\"attempt_observation_seconds\": 30, \"chunk_feedback_window_ms\": 200, \"chunk_throughput_min_samples\": 3, \"hedge_max_ms\": 2000, \"hedge_min_ms\": 100, \"hedge_min_samples\": 20, \"keepalive_seconds\": 30, \"metric_ttl_seconds\": 300, \"resume_ttl_seconds\": 300, \"unmeasured_hedge_ms\": 500}, \"transport_version\": 1}")
BROKERS = CATALOG["brokers"]
BROKER_IDS = frozenset(BROKERS)
