platform :ios, '15.0'

use_frameworks!

target 'GalaxySSI' do
  # Keep the iOS transport on the same libsignal protocol as Android.
  pod 'LibSignalClient', git: 'https://github.com/signalapp/libsignal.git', tag: 'v0.94.2'
end
