// Generated by tools/generate_mqtt_catalog.py; do not edit.
package com.galaxyssi.chat

internal object MqttBrokerCatalog {
    const val TRANSPORT_VERSION = 1
    data class Endpoint(val host: String, val tlsPort: Int) {
        val serverUri: String get() = "ssl://$host:$tlsPort"
    }
    val brokers = mapOf(
        "emqx" to Endpoint("broker.emqx.io", 8883),
        "hivemq" to Endpoint("broker.hivemq.com", 8883),
        "mosquitto" to Endpoint("test.mosquitto.org", 8886)
    )
    const val PACKET_BYTES = 1048576
    const val SMALL_PACKET_BYTES = 65536
    const val INFLIGHT_PACKETS = 12
    const val CONTROL_RESERVE = 2
    const val INFLIGHT_BYTES = 8388608
    const val PEER_INFLIGHT_BYTES = 2097152
    const val MAX_PEER_ROUTES = 10000
    const val MAX_ATTEMPTS = 4096
    const val KEEPALIVE_SECONDS = 30
    const val METRIC_TTL_MS = 300000L
    const val RESUME_TTL_MS = 300000L
    const val ATTEMPT_OBSERVATION_MS = 30000L
    const val HEDGE_MIN_SAMPLES = 20
    const val HEDGE_MIN_MS = 100L
    const val HEDGE_MAX_MS = 2000L
    const val UNMEASURED_HEDGE_MS = 500L
}
