"""Generate packaged broker catalogs from config/mqtt-multipath.json."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def outputs(root: Path = ROOT) -> dict[Path, str]:
    spec = json.loads((root / "config/mqtt-multipath.json").read_text(encoding="utf-8"))
    if set(spec) != {"transport_version", "selection", "brokers", "limits", "timing"}:
        raise ValueError("unexpected catalog field; default/manual provider controls are not supported")
    if type(spec["transport_version"]) is not int or spec["transport_version"] != 1:
        raise ValueError("unsupported transport catalog version")
    if spec["selection"] != "automatic" or set(spec["brokers"]) != {"emqx", "hivemq", "mosquitto"}:
        raise ValueError("the catalog requires three equal automatic candidates")
    for broker in spec["brokers"].values():
        if (set(broker) != {"host", "tls_port"} or not isinstance(broker["host"], str)
                or not re.fullmatch(r"[A-Za-z0-9](?:[A-Za-z0-9.-]{0,251}[A-Za-z0-9])?", broker["host"])
                or type(broker["tls_port"]) is not int or not 1 <= broker["tls_port"] <= 65535):
            raise ValueError("invalid TLS endpoint")
    if any(type(value) is not int or value <= 0 for value in (spec["limits"] | spec["timing"]).values()):
        raise ValueError("catalog budgets must be positive integers")
    limits, timing = spec["limits"], spec["timing"]
    if (limits["reserved_control_packets"] >= limits["global_inflight_packets"]
            or not limits["small_packet_bytes"] <= limits["encoded_packet_bytes"] <= limits["per_peer_inflight_bytes"] <= limits["global_inflight_bytes"]
            or not timing["hedge_min_ms"] <= timing["unmeasured_hedge_ms"] <= timing["hedge_max_ms"]):
        raise ValueError("invalid catalog capacity or hedge bounds")
    python = ('# Generated by tools/generate_mqtt_catalog.py; do not edit.\n'
              'import json\n\n'
              f'CATALOG = json.loads({json.dumps(json.dumps(spec, sort_keys=True))})\n'
              'BROKERS = CATALOG["brokers"]\n'
              'BROKER_IDS = frozenset(BROKERS)\n')
    entries = ',\n'.join(f'        "{key}" to Endpoint("{value["host"]}", {value["tls_port"]})'
                          for key, value in sorted(spec["brokers"].items()))
    kotlin = f'''// Generated by tools/generate_mqtt_catalog.py; do not edit.
package com.galaxyssi.chat

internal object MqttBrokerCatalog {{
    const val TRANSPORT_VERSION = {spec["transport_version"]}
    data class Endpoint(val host: String, val tlsPort: Int) {{
        val serverUri: String get() = "ssl://$host:$tlsPort"
    }}
    val brokers = mapOf(
{entries}
    )
    const val PACKET_BYTES = {spec["limits"]["encoded_packet_bytes"]}
    const val SMALL_PACKET_BYTES = {spec["limits"]["small_packet_bytes"]}
    const val INFLIGHT_PACKETS = {spec["limits"]["global_inflight_packets"]}
    const val CONTROL_RESERVE = {spec["limits"]["reserved_control_packets"]}
    const val INFLIGHT_BYTES = {spec["limits"]["global_inflight_bytes"]}
    const val PEER_INFLIGHT_BYTES = {spec["limits"]["per_peer_inflight_bytes"]}
    const val MAX_PEER_ROUTES = {spec["limits"]["max_peer_routes"]}
    const val MAX_ATTEMPTS = {spec["limits"]["max_tracked_attempts"]}
    const val KEEPALIVE_SECONDS = {spec["timing"]["keepalive_seconds"]}
    const val METRIC_TTL_MS = {spec["timing"]["metric_ttl_seconds"] * 1000}L
    const val RESUME_TTL_MS = {spec["timing"]["resume_ttl_seconds"] * 1000}L
    const val HEDGE_MIN_MS = {spec["timing"]["hedge_min_ms"]}L
    const val HEDGE_MAX_MS = {spec["timing"]["hedge_max_ms"]}L
    const val UNMEASURED_HEDGE_MS = {spec["timing"]["unmeasured_hedge_ms"]}L
}}
'''
    return {
        root / "apps/desktop/core/galaxyssi-link/backend/mqtt_broker_catalog.py": python,
        root / "apps/android/app/src/main/java/com/galaxyssi/chat/MqttBrokerCatalog.kt": kotlin,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"stale generated broker catalog: {path}")
        else:
            path.write_text(content, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
